import { randomBytes, randomUUID } from "node:crypto";
import { spawn } from "node:child_process";
import { lstat, mkdir, readFile, readdir, realpath, rm, stat } from "node:fs/promises";
import { createServer } from "node:net";
import { dirname, isAbsolute, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { acquireDirectoryLock, assertNoSymlinksInTree, atomicCreateFile, atomicWriteFile, isProcessAlive as processAlive } from "../lib/file-storage-lock.mjs";

const MANAGED_ENV_MARKER = "# harness-arena-init:v2";
const NEXT_DEV_ENV_FILES = new Set([".env", ".env.local", ".env.development", ".env.development.local"]);
const INHERITED_ALLOWLIST = new Set(["PATH", "TMPDIR", "LANG", "LC_ALL", "TERM", "COLORTERM", "CI", "NO_COLOR", "FORCE_COLOR", "SystemRoot", "ComSpec"]);
const SAFE_LOCAL_KEYS = new Set(["STORAGE", "LOCAL_STORAGE_DIR", "AUTH_SECRET", "LOCAL_INSTANCE_NONCE", "HARNESS_LOCAL_INIT", "LOCAL_NEUTRALIZED_ENV_KEYS", "NODE_ENV"]);
const REQUIRED_NODE_VERSION = [20, 9, 0];
const DEFAULT_INIT_LOCK_TIMEOUT_MS = 120_000;
const SUPERVISOR_PATH = fileURLToPath(new URL("./init-process-supervisor.mjs", import.meta.url));
const SUPERVISOR_OWNERSHIP = new WeakMap();
export const INIT_CANCELLATION_PHASES = Object.freeze([
  "lock_wait", "pre_server_spawn", "ownership_handshake", "readiness_poll", "active_prerequisite", "server_lifecycle",
]);

export function choosePort(worktree) {
  let hash = 2166136261;
  for (const char of resolve(worktree)) hash = Math.imul(hash ^ char.charCodeAt(0), 16777619);
  return 20000 + ((hash >>> 0) % 10000);
}

export function assertNodeVersion(version = process.versions.node) {
  const match = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.exec(String(version));
  const parsed = match?.slice(1).map(Number);
  const valid = parsed?.length === 3 && parsed.every(Number.isSafeInteger);
  let comparison = 0;
  if (valid) {
    for (let index = 0; index < REQUIRED_NODE_VERSION.length; index++) {
      if (parsed[index] === REQUIRED_NODE_VERSION[index]) continue;
      comparison = parsed[index] > REQUIRED_NODE_VERSION[index] ? 1 : -1;
      break;
    }
  }
  if (!valid || comparison < 0) throw new Error(`Node.js 20.9.0+ is required (found ${version})`);
}

export function validateStartup({ node, nodeVersion = process.versions.node, pnpm, portAvailable, stalePid }) {
  if (!node) throw new Error("Node.js 20.9.0+ is required");
  assertNodeVersion(nodeVersion);
  if (!pnpm) throw new Error("pnpm is required");
  if (!portAvailable) throw new Error("selected port is already in use");
  if (stalePid) throw new Error("stale PID metadata detected; run ./scripts/init.sh --reset");
}

export function isPortAvailable(port) {
  return new Promise((resolvePort) => {
    const server = createServer();
    server.once("error", () => resolvePort(false));
    server.listen(port, "127.0.0.1", () => server.close(() => resolvePort(true)));
  });
}

export async function chooseAvailablePort(worktree) {
  const base = choosePort(worktree);
  for (let offset = 0; offset < 100; offset++) {
    const candidate = 20000 + ((base - 20000 + offset) % 10000);
    if (await isPortAvailable(candidate)) return candidate;
  }
  throw new Error("no available deterministic local port found in the worktree range");
}

export function localEnv(worktree, { write = false, beforePublish } = {}) {
  const root = resolve(worktree, ".harness-arena", "local-data");
  const content = `${MANAGED_ENV_MARKER}\n# Local-only; never copy production secrets here.\nSTORAGE=file\nLOCAL_STORAGE_DIR=${root}\nAUTH_SECRET=${randomBytes(32).toString("base64url")}\n`;
  if (!write) return content;
  return writeLocalEnv(worktree, content, beforePublish);
}

async function writeLocalEnv(worktree, content, beforePublish) {
  const path = join(resolve(worktree), ".env.local");
  try { await atomicCreateFile(path, content, 0o600, resolve(worktree), { beforePublish }); } catch (error) {
    if (error?.code === "EEXIST") throw new Error(`.env.local already exists at ${path}; refusing to overwrite operator file`);
    throw error;
  }
  return path;
}

export async function readManagedLocalConfig(worktree) {
  const path = join(resolve(worktree), ".env.local");
  let content;
  try { content = await readFile(path, "utf8"); } catch (error) {
    if (error?.code !== "ENOENT") throw error;
    await localEnv(worktree, { write: true });
    content = await readFile(path, "utf8");
  }
  if ((await stat(path)).mode & 0o077) throw new Error(`init-managed .env.local must not be readable by group or others: ${path}`);
  const legacyManaged = content.startsWith("# Generated by scripts/init.sh. Local-only; never copy production secrets here.");
  if (!content.startsWith(MANAGED_ENV_MARKER) && !legacyManaged) throw new Error(`existing .env.local is not init-managed; refusing to overwrite it`);
  const parsed = parseEnvAssignments(content);
  const expectedRoot = resolve(worktree, ".harness-arena", "local-data");
  if (parsed.STORAGE !== "file" || resolve(parsed.LOCAL_STORAGE_DIR ?? "") !== expectedRoot || !parsed.AUTH_SECRET) {
    throw new Error("init-managed .env.local has unsafe or incomplete local configuration");
  }
  return { STORAGE: "file", LOCAL_STORAGE_DIR: expectedRoot, AUTH_SECRET: parsed.AUTH_SECRET };
}

export async function safeChildEnv(worktree, parentEnv, localConfig) {
  const child = {};
  for (const key of INHERITED_ALLOWLIST) if (typeof parentEnv[key] === "string" && parentEnv[key] !== "") child[key] = parentEnv[key];
  Object.assign(child, {
    NODE_ENV: "development",
    HARNESS_LOCAL_INIT: "1",
    STORAGE: "file",
    LOCAL_STORAGE_DIR: localConfig.LOCAL_STORAGE_DIR,
    AUTH_SECRET: localConfig.AUTH_SECRET,
    LOCAL_INSTANCE_NONCE: localConfig.LOCAL_INSTANCE_NONCE ?? "",
  });
  const discovered = await discoverNextEnvKeys(worktree);
  const neutralized = [];
  for (const key of discovered) {
    if (SAFE_LOCAL_KEYS.has(key)) continue;
    child[key] = "";
    neutralized.push(key);
  }
  child.LOCAL_NEUTRALIZED_ENV_KEYS = neutralized.sort().join(",");
  return child;
}

export async function discoverNextEnvKeys(worktree) {
  let names = [];
  try { names = await readdir(resolve(worktree)); } catch (error) { if (error?.code !== "ENOENT") throw error; }
  const keys = new Set();
  for (const name of names.filter((candidate) => NEXT_DEV_ENV_FILES.has(candidate))) {
    const assignments = parseEnvAssignments(await readFile(join(resolve(worktree), name), "utf8"));
    for (const key of Object.keys(assignments)) keys.add(key);
  }
  return keys;
}

function parseEnvAssignments(content) {
  const assignments = {};
  for (const line of content.split(/\r?\n/)) {
    const match = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/.exec(line);
    if (!match) continue;
    let value = match[2].trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    assignments[match[1]] = value;
  }
  return assignments;
}

export function isProcessAlive(pid) { return processAlive(pid); }

export async function acquireInitLock(lockPath, options) {
  return acquireDirectoryLock(lockPath, { timeoutMs: DEFAULT_INIT_LOCK_TIMEOUT_MS, confinementRoot: dirname(lockPath), ...options });
}

export async function spawnSupervisedProcess(command, args, options = {}, {
  signal,
  spawnImpl = spawn,
  handshakeTimeoutMs = 10_000,
} = {}) {
  signal?.throwIfAborted();
  const nonce = randomUUID();
  const requestedStdio = options.stdio ?? "ignore";
  const childStdio = Array.isArray(requestedStdio)
    ? requestedStdio
    : Array.from({ length: 3 }, () => requestedStdio);
  const supervisorStdio = [...childStdio, "ipc"];
  const config = JSON.stringify({ command, args, cwd: options.cwd, stdioLength: childStdio.length });
  let child;
  try {
    child = spawnImpl(process.execPath, [SUPERVISOR_PATH], {
      cwd: options.cwd,
      detached: true,
      env: { ...(options.env ?? process.env), HARNESS_INIT_SUPERVISOR_NONCE: nonce, HARNESS_INIT_SUPERVISOR_CONFIG: config },
      stdio: supervisorStdio,
    });
  } catch (error) { throw error; }

  let resolveOutcome;
  const outcome = new Promise((resolve) => { resolveOutcome = resolve; });
  let outcomeSettled = false;
  const onOutcome = (message) => {
    if (message?.type !== "outcome" || message.nonce !== nonce || message.supervisorPid !== child.pid || outcomeSettled) return;
    outcomeSettled = true;
    resolveOutcome(message.error ? { error: Object.assign(new Error(message.error.message), { code: message.error.code }) } : { code: message.code, signal: message.signal });
  };
  child.on("message", onOutcome);
  child.once("exit", (code, exitSignal) => {
    if (!outcomeSettled) { outcomeSettled = true; resolveOutcome({ error: new Error(`supervisor exited before command outcome (${exitSignal ?? code})`) }); }
  });
  const owned = Object.freeze({ child, supervisorPid: child.pid, outcome });
  const record = { child, nonce, supervisorPid: child.pid, groupPid: undefined };
  SUPERVISOR_OWNERSHIP.set(owned, record);
  try {
    const started = await supervisorHandshake(child, nonce, handshakeTimeoutMs, signal);
    record.groupPid = started.groupPid;
    return owned;
  } catch (error) {
    try { child.send({ type: "terminate", nonce, graceMs: 50, killWaitMs: 500 }); } catch {}
    await waitForChildExit(child, 1_500).catch(() => {});
    throw error;
  }
}

async function supervisorHandshake(child, nonce, timeoutMs, signal) {
  return new Promise((resolveHandshake, rejectHandshake) => {
    let settled = false;
    let startRequested = false;
    const timer = setTimeout(() => finish(new Error(`supervisor ownership handshake timed out after ${timeoutMs}ms`)), timeoutMs);
    timer.unref();
    const onMessage = (message) => {
      if (message?.nonce !== nonce || message.supervisorPid !== child.pid) return;
      if (message.type === "supervisor-ready" && !startRequested) {
        startRequested = true;
        try { signal?.throwIfAborted(); child.send({ type: "start", nonce }); }
        catch (error) { finish(error); }
      } else if (message.type === "started" && startRequested) {
        if (!Number.isSafeInteger(message.groupPid) || message.groupPid <= 0 || message.groupPid === child.pid
          || !Number.isSafeInteger(message.commandPid) || message.commandPid <= 0) {
          finish(new Error("supervisor returned invalid command group ownership"));
        } else finish(undefined, message);
      }
    };
    const onError = (error) => finish(error);
    const onExit = (code, exitSignal) => finish(new Error(`supervisor exited before ownership handshake (${exitSignal ?? code})`));
    const onAbort = () => finish(signal.reason instanceof Error ? signal.reason : new Error("init cancelled"));
    child.on("message", onMessage);
    child.once("error", onError);
    child.once("exit", onExit);
    signal?.addEventListener("abort", onAbort, { once: true });
    if (signal?.aborted) onAbort();
    function finish(error, value) {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      child.off("message", onMessage);
      child.off("error", onError);
      child.off("exit", onExit);
      signal?.removeEventListener("abort", onAbort);
      if (error) rejectHandshake(error); else resolveHandshake(value);
    }
  });
}

export async function terminateOwnedSupervisor(owned, {
  graceMs = 500,
  killWaitMs = 1_000,
  beforeEscalate,
} = {}) {
  const record = SUPERVISOR_OWNERSHIP.get(owned);
  if (!record || owned.child !== record.child || owned.supervisorPid !== record.supervisorPid
    || !Number.isSafeInteger(record.groupPid) || !liveChild(record.child) || !record.child.connected) return false;
  const completed = waitForAuthenticatedExit(record, "group-reaped", graceMs + killWaitMs + 1_000);
  try { record.child.send({ type: "terminate", nonce: record.nonce, graceMs, killWaitMs }); }
  catch { return false; }
  if (beforeEscalate) await beforeEscalate();
  return completed;
}

function liveChild(child) { return child.exitCode === null && child.signalCode === null; }

function waitForChildExit(child, timeoutMs) {
  if (!liveChild(child)) return Promise.resolve(true);
  return new Promise((resolveExit) => {
    const timer = setTimeout(() => finish(false), timeoutMs);
    child.once("exit", onExit);
    function onExit() { finish(true); }
    function finish(value) { clearTimeout(timer); child.off("exit", onExit); resolveExit(value); }
  });
}

export async function detachOwnedSupervisor(owned) {
  const record = SUPERVISOR_OWNERSHIP.get(owned);
  if (!record || !liveChild(record.child)) return false;
  const detached = waitForAuthenticatedMessage(record, "detached", 500);
  try { record.child.send({ type: "detach", nonce: record.nonce }); } catch { return false; }
  if (!await detached || !liveChild(record.child)) return false;
  record.child.unref();
  return true;
}

function waitForAuthenticatedMessage(record, type, timeoutMs) {
  return new Promise((resolveMatched) => {
    let settled = false;
    const timer = setTimeout(() => finish(false), timeoutMs);
    timer.unref();
    const onMessage = (message) => {
      if (authenticatedSupervisorMessage(message, record, type)) finish(true);
    };
    const onExit = () => finish(false);
    record.child.on("message", onMessage);
    record.child.once("exit", onExit);
    function finish(value) {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      record.child.off("message", onMessage);
      record.child.off("exit", onExit);
      resolveMatched(value);
    }
  });
}

function waitForAuthenticatedExit(record, type, timeoutMs) {
  return new Promise((resolveComplete) => {
    let settled = false;
    let acknowledged = false;
    let exited = !liveChild(record.child);
    const timer = setTimeout(() => finish(false), timeoutMs);
    const onMessage = (message) => {
      if (!authenticatedSupervisorMessage(message, record, type)) return;
      acknowledged = true;
      if (exited) finish(true);
    };
    const onExit = () => {
      exited = true;
      if (acknowledged) finish(true);
    };
    record.child.on("message", onMessage);
    record.child.once("exit", onExit);
    function finish(value) {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      record.child.off("message", onMessage);
      record.child.off("exit", onExit);
      resolveComplete(value);
    }
  });
}

function authenticatedSupervisorMessage(message, record, type) {
  return message?.type === type && message.nonce === record.nonce
    && message.supervisorPid === record.supervisorPid && message.groupPid === record.groupPid;
}

export async function failTimedOutStart({ worktree, owned, pid, nonce, port, logPath }) {
  if (!owned || pid !== owned.supervisorPid) throw new Error("timed-out start requires the matching live supervisor handle");
  await terminateOwnedSupervisor(owned);
  const state = resolve(worktree, ".harness-arena");
  await mkdir(state, { recursive: true, mode: 0o700 });
  await atomicWriteFile(join(state, "init-failure.json"), JSON.stringify({ reason: "readiness_timeout", pid, nonce, port, log: resolve(logPath), occurred_at: new Date().toISOString() }));
  await rm(join(state, "init.pid"), { force: true });
}

export async function readInstanceMetadata(state) {
  try {
    const value = JSON.parse(await readFile(join(state, "init.pid"), "utf8"));
    if (!Number.isSafeInteger(value.pid) || !Number.isSafeInteger(value.port) || typeof value.nonce !== "string" || !value.nonce) return undefined;
    return value;
  } catch { return undefined; }
}

export async function writeInstanceMetadata(state, metadata, { beforePublish } = {}) {
  await atomicWriteFile(join(state, "init.pid"), JSON.stringify(metadata), 0o600, undefined, { beforePublish });
}

export async function removeInstanceMetadataIfOwned(state, metadata) {
  const current = await readInstanceMetadata(state);
  if (current?.pid === metadata.pid && current?.nonce === metadata.nonce) await rm(join(state, "init.pid"), { force: true });
}

export function waitForOwnershipHandshake(child, expected, options = 10_000) {
  const { timeoutMs, signal } = typeof options === "number"
    ? { timeoutMs: options, signal: undefined }
    : { timeoutMs: options?.timeoutMs ?? 10_000, signal: options?.signal };
  return new Promise((resolveHandshake, rejectHandshake) => {
    const channel = child.stdio?.[3];
    if (!channel) {
      rejectHandshake(new Error("local wrapper ownership handshake channel is unavailable"));
      return;
    }
    let buffer = "";
    let settled = false;
    const timer = setTimeout(() => finish(new Error(`local wrapper ownership handshake timed out after ${timeoutMs}ms`)), timeoutMs);
    const onError = (error) => finish(error);
    const onExit = (code, signal) => finish(new Error(`local wrapper exited before ownership handshake (${signal ?? code})`));
    const onAbort = () => finish(signal.reason instanceof Error ? signal.reason : new Error("ownership handshake cancelled"));
    const onData = (chunk) => {
      buffer += chunk;
      const newline = buffer.indexOf("\n");
      if (newline < 0) return;
      try {
        const message = JSON.parse(buffer.slice(0, newline));
        if (message?.type !== "ownership-durable"
          || message.pid !== expected.pid
          || message.nonce !== expected.nonce
          || message.port !== expected.port) {
          finish(new Error("local wrapper returned mismatched ownership metadata"));
          return;
        }
        finish(undefined, message);
      } catch (error) { finish(error); }
    };
    channel.on("data", onData);
    channel.once("error", onError);
    child.once("error", onError);
    child.once("exit", onExit);
    signal?.addEventListener("abort", onAbort, { once: true });
    if (signal?.aborted) onAbort();

    function finish(error, value) {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      channel.off("data", onData);
      channel.off("error", onError);
      child.off("error", onError);
      child.off("exit", onExit);
      signal?.removeEventListener("abort", onAbort);
      if (error) rejectHandshake(error); else resolveHandshake(value);
    }
  });
}

export async function probeInstance(metadata, timeoutMs = 1000, signal) {
  if (!isProcessAlive(metadata.pid)) return undefined;
  try {
    const timeoutSignal = AbortSignal.timeout(timeoutMs);
    const response = await fetch(`http://127.0.0.1:${metadata.port}/api/ready`, { signal: signal ? AbortSignal.any([signal, timeoutSignal]) : timeoutSignal });
    if (!response.ok) return undefined;
    const body = await response.json();
    return body.pid === metadata.pid && body.nonce === metadata.nonce && body.seeded === true && body.writable === true ? body : undefined;
  } catch { return undefined; }
}

export async function probeLocalInstance(metadata, timeoutMs = 1000, signal) {
  if (!isProcessAlive(metadata.pid)) return false;
  try {
    const timeoutSignal = AbortSignal.timeout(timeoutMs);
    const response = await fetch(`http://127.0.0.1:${metadata.port}/api/local-instance`, {
      headers: { "x-harness-local-instance-nonce": metadata.nonce },
      redirect: "error",
      signal: signal ? AbortSignal.any([signal, timeoutSignal]) : timeoutSignal,
    });
    return response.status === 204;
  } catch { return false; }
}

export async function resetLocalData(worktree) {
  const root = await realpath(resolve(worktree));
  const state = join(root, ".harness-arena");
  const stateInfo = await safeLstat(state);
  if (!stateInfo) return { removed: false, stale_pid_recovered: false, storage: join(state, "local-data") };
  if (stateInfo.isSymbolicLink()) throw new Error("refusing reset: state directory is a symlink and is not confined");
  if (!stateInfo.isDirectory()) throw new Error("refusing reset: state path is not a directory");
  assertWithin(root, await realpath(state));
  await assertNoSymlinksInTree(state);
  const ownership = await readPidOwnership(state);
  if (ownership.pid && isProcessAlive(ownership.pid)) throw new Error(`refusing reset: local instance ${ownership.pid} is still running`);
  const data = join(state, "local-data");
  const dataInfo = await safeLstat(data);
  if (dataInfo?.isSymbolicLink()) throw new Error("refusing reset: local data is a symlink and is not confined");
  if (dataInfo) assertWithin(state, await realpath(data));
  await rm(data, { recursive: true, force: true });
  await rm(join(state, "init.pid"), { force: true });
  return { removed: Boolean(dataInfo), stale_pid_recovered: ownership.present, storage: data };
}

async function readPidOwnership(state) {
  let raw;
  try { raw = await readFile(join(state, "init.pid"), "utf8"); } catch (error) {
    if (error?.code === "ENOENT") return { present: false, pid: undefined };
    throw error;
  }
  let value;
  try { value = JSON.parse(raw); } catch { throw new Error("refusing reset: unrecognized PID metadata"); }
  const pid = Number.isSafeInteger(value) ? value : value?.pid;
  if (!Number.isSafeInteger(pid) || pid <= 0) throw new Error("refusing reset: unrecognized PID metadata");
  return { present: true, pid };
}

async function safeLstat(path) {
  try { return await lstat(path); } catch (error) { if (error?.code === "ENOENT") return undefined; throw error; }
}

function assertWithin(parent, candidate) {
  const rel = relative(parent, candidate);
  if (!rel || (!rel.startsWith("..") && !isAbsolute(rel))) return;
  throw new Error(`path is not confined to ${parent}: ${candidate}`);
}

export async function inspectSafeStateDirectory(worktree) {
  const root = await realpath(resolve(worktree));
  const state = join(root, ".harness-arena");
  const info = await safeLstat(state);
  if (info?.isSymbolicLink()) throw new Error("state directory must not be a symlink");
  if (info && !info.isDirectory()) throw new Error("state path must be a directory");
  if (!info) return { state, exists: false };
  assertWithin(root, await realpath(state));
  await assertNoSymlinksInTree(state);
  const data = join(state, "local-data");
  const dataInfo = await safeLstat(data);
  if (dataInfo?.isSymbolicLink()) throw new Error("local data directory must not be a symlink");
  if (dataInfo && !dataInfo.isDirectory()) throw new Error("local data path must be a directory");
  if (dataInfo) assertWithin(state, await realpath(data));
  return { state, exists: true };
}

export async function assertSafeStateDirectory(worktree) {
  let inspected = await inspectSafeStateDirectory(worktree);
  if (!inspected.exists) {
    try { await mkdir(inspected.state, { recursive: false, mode: 0o700 }); }
    catch (error) { if (error?.code !== "EEXIST") throw error; }
    inspected = await inspectSafeStateDirectory(worktree);
  }
  return inspected.state;
}
