import { chmod, open } from "node:fs/promises";
import { randomBytes } from "node:crypto";
import { join, resolve } from "node:path";

export function choosePort(worktree) {
  let hash = 2166136261;
  for (const char of resolve(worktree)) hash = Math.imul(hash ^ char.charCodeAt(0), 16777619);
  return 20000 + ((hash >>> 0) % 10000);
}

export function validateStartup({ node, pnpm, portAvailable, stalePid }) {
  if (!node) throw new Error("Node.js 20+ is required");
  if (!pnpm) throw new Error("pnpm is required");
  if (!portAvailable) throw new Error("selected port is already in use");
  if (stalePid) throw new Error("stale PID metadata detected; run ./scripts/init.sh --reset");
}

export function localEnv(worktree, { write = false } = {}) {
  const root = resolve(worktree, ".harness-arena", "local-data");
  const content = `# Generated by scripts/init.sh. Local-only; never copy production secrets here.\nSTORAGE=file\nLOCAL_STORAGE_DIR=${root}\nAUTH_SECRET=${randomBytes(32).toString("base64url")}\n`;
  if (!write) return content;
  return writeLocalEnv(worktree, content);
}

async function writeLocalEnv(worktree, content) {
  const path = join(resolve(worktree), ".env.local");
  let file;
  try { file = await open(path, "wx", 0o600); } catch (error) {
    if (error?.code === "EEXIST") throw new Error(`.env.local already exists at ${path}; refusing to overwrite operator file`);
    throw error;
  }
  await file.writeFile(content);
  await file.close();
  await chmod(path, 0o600);
  return path;
}
